project:
  type: website
  output-dir: docs

website:
  title: "ABCs of data science"
  favicon: favicon.ico
  navbar:
    logo: abc_logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gclen/abcs-of-data-science-quarto 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



